### ISSUE TITLE
app specific website URL is same for both apps?

### ISSUE THREAD

**Issue by jindam-vani** [SecUSo/privacy-friendly-circuit-training-exercises#25]
@udenr 
* ```https://secuso.aifb.kit.edu/english/Interval_Timer_and_Circuit_Training.php``` contain links for fdroid and github_ Privacy Friendly Interval Timer app only
* **same URL** for both Privacy Friendly Interval Timer app and Privacy Friendly Circuit Training App_ is this intended?

**Comment by udenr** [comment]
Thank you for pointing this out. 

- I have updated the page, there are now links for both apps.
- Yes, it is intended that both apps are on one page.
