### ISSUE TITLE
Add to official F-Droid repository

### ISSUE THREAD

**Issue by geronimoge** [SecUSo/privacy-friendly-circuit-training-exercises#9]
Unfortunately the app isn't available in the F-Droid repository.
It would be great to see it there.

**Comment by Kamuno** [comment]
The app is in process of being added already. See https://gitlab.com/fdroid/rfp/issues/780

**Comment by geronimoge** [comment]
Is there any chance to push this?

**Comment by Poussinou** [comment]
@geronimoge The app is now available in F-Droid
